INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Computador A', 'I7 16GB SSD1', 5403);
INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Computador B', 'I7 16GB SSD1', 9864);
INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Computador C', 'I7 16GB SSD1', 1234);
INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Computador D', 'I7 16GB SSD1', 9764);
